name: "Build Next.js"
description: "Builds a Next.js application"
inputs:
  version:
    required: true
    description: "Application version"
  minimumCoverage:
    required: false
    description: "Minimum code coverage percentage"
    default: "0"
  githubToken:
    required: true
    description: "Github token for publishing"
  testProjectPath:
    required: false
    description: "Path to project/tests if different from root"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install Dependencies & Build
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        TEST_PROJECT_PATH: ${{ inputs.testProjectPath }}
        GHCR_USER: ${{ github.actor }}
        GHCR_TOKEN: ${{ inputs.githubToken }}
      run: |
        echo "Building Next.js application version $VERSION"
        npm install
        npm run build