name: "Generate SBOM"
description: "Generates an SBOM for each project"
runs:
  using: "composite"
  steps:
    - name: Generate SBOM
      shell: bash
      run: |
        dotnet tool install --global CycloneDX
          PATH=/root/.dotnet/tools:$PATH
          mkdir -p out
          find . -path '**/*.csproj' -print0 | while IFS= read -r -d $'\0' file; do 
            name=$(basename "$file" .csproj)
            dotnet CycloneDX "$file" --output out --filename "$name".sbom.json --json
          done