name: "Check Licenses"
description: "Checks licenses against an allowed list and outputs a report artifact for each project"
inputs:
  allowed_licenses_path:
    required: true
    description: "Path to the allowed licenses JSON file"
  ignored_packages_path:
    required: true
    description: "Path to the ignored packages JSON file"
  githubToken:
    required: true
    description: "Github Token"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: |
          9.x
          10.x
    - name: Install jq
      uses: dcarbone/install-jq-action@b7ef57d46ece78760b4019dbc4080a1ba2a40b45 # v3.2.0
    - name: Check Licenses for each project
      shell: bash
      env:
        GHCR_USER: ${{ github.actor }}
        GHCR_TOKEN: ${{ inputs.githubToken }}
        NuGetPackageSourceCredentials_github: "Username=${{ github.actor }};Password=${{ inputs.githubToken }}"
        ALLOWED_LICENSES_PATH: ${{ inputs.allowed_licenses_path }}
        IGNORED_PACKAGES_PATH: ${{ inputs.ignored_packages_path }}
      run: |
        dotnet nuget add source \
          --name "github" \
          "https://nuget.pkg.github.com/innago-property-management/index.json"
        
        dotnet restore
        dotnet tool install --global nuget-license || continue
        PATH=/root/.dotnet/tools:$PATH
        
        solution=$(find . -type f -name '*.slnx')
        
        if [[ -z $solution ]]; then
          solution=$(find . -type f -name '*.sln')
        fi
        
        mkdir out
        output_path="out/licenses.json"
        nuget-license \
         --input "$solution" \
         --include-shared-projects \
         --output jsonpretty \
         --allowed-license-types "$ALLOWED_LICENSES_PATH" \
         --ignored-packages "$IGNORED_PACKAGES_PATH" \
         | tee "$output_path" \
         | jq '.[] | select(.ValidationErrors != null)'
    - uses: buildingcash/json-to-markdown-table-action@b442169239ef35f1dc4e5c8c3d47686c081a7e65 #v1.1.0
      if: always()
      name: table
      id: table
      with:
        json_file_path: "out/licenses.json"
    - name: Output to markdown
      if: always()
      shell: bash
      run: echo "${{ steps.table.outputs.table }}" >> $GITHUB_STEP_SUMMARY
