name: "Build, Publish, and Sign a Container Image"
description: "Docker build, push; Cosign"
inputs:
  registry:
    required: false
    default: ghcr.io
    description: "Registry"
  username:
    required: true
    description: "GitHub Actor"
  password:
    required: true
    description: "GitHub Token"
  version:
    required: true
    description: "Semantic Version"
  imageName:
    required: true
    description: "Image Name"
  organizationName:
    required: true
    description: "Org name"
  imageTitle:
    required: true
    description: "Title of the image from the repository"
  imageDescription:
    required: true
    description: "Description of the image from the repository"
  repositoryUrl:
    required: true
    description: "URL of the repository"
  sha:
    required: true
    description: "The commit SHA"
  cosignKey:
    required: true
    description: "Cosign key"
  cosignPassword:
    required: true
    description: "Password for Cosign key"
  buildArgs:
    required: false
    description: "Build arguments for Docker build (e.g., NUGET_SOURCE_URL=...)"
    default: ''
  secrets:
    required: false # Set to 'true' if the NuGet password is always required
    description: "Secrets to pass to the Docker build (e.g., nuget_password=...)"
    default: '' # Provide a default empty string if not always required
  migrationsDockerfileContext:
    required: false
    default: '.'
    description: "The build context for the migrations Docker image. Relative to repository root."
  migrationsDockerfilePath:
    required: false
    default: ''
    description: "The path to the migrations Dockerfile relative to the build context. Leave unset to skip."
  platforms:
    required: false
    default: 'linux/amd64,linux/arm64'
    description: "Target platforms for the Docker build (e.g., 'linux/amd64,linux/arm64' or 'linux/arm64')"
runs:
  using: "composite"
  steps:
    - name: Set up cosign
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0 (installs cosign v3.x)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # 3.4.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Publish container image
      id: publish
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # 6.15.0
      env:
        VERSION: ${{ inputs.version }}
        IMAGE_NAME: ${{ inputs.imageName }}
      with:
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: ${{ inputs.platforms }}
        tags: |
          ${{ inputs.registry }}/${{ inputs.organizationName }}/${{ inputs.imageName }}:${{ inputs.version }}
        labels: |
          org.opencontainers.image.title=${{ inputs.imageTitle }}
          org.opencontainers.image.description=${{ inputs.imageDescription }}
          org.opencontainers.image.url=${{ inputs.repositoryUrl }}
          org.opencontainers.image.revision=${{ inputs.sha }}
          org.opencontainers.image.version=${{ inputs.version }}
        annotations: |
          org.opencontainers.image.title=${{ inputs.imageTitle }}
          org.opencontainers.image.description=${{ inputs.imageDescription }}
          org.opencontainers.image.url=${{ inputs.repositoryUrl }}
          org.opencontainers.image.revision=${{ inputs.sha }}
          org.opencontainers.image.version=${{ inputs.version }}
        build-args: ${{ inputs.buildArgs }}
        secrets: ${{ inputs.secrets }}
        cache-from: type=gha, scope=${{ github.repository }}
        cache-to: type=gha, mode=max, scope=${{ github.repository }}
    - name: Publish migrations image
      id: publish-migrations
      if: ${{ inputs.migrationsDockerfilePath && (inputs.migrationsDockerfilePath) != '' }}
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # 6.15.0
      env:
        VERSION: ${{ inputs.version }}
        IMAGE_NAME: ${{ inputs.imageName }}-migrations
      with:
        push: true
        builder: ${{ steps.buildx.outputs.name }}
        context: ${{ inputs.migrationsDockerfileContext }}
        file: ${{ inputs.migrationsDockerfilePath }}
        platforms: ${{ inputs.platforms }}
        tags: |
          ${{ inputs.registry }}/${{ inputs.organizationName }}/${{ inputs.imageName }}-migrations:${{ inputs.version }}
        labels: |
          org.opencontainers.image.title=${{ inputs.imageTitle }}-migrations
          org.opencontainers.image.description=${{ inputs.imageDescription }}
          org.opencontainers.image.url=${{ inputs.repositoryUrl }}
          org.opencontainers.image.revision=${{ inputs.sha }}
          org.opencontainers.image.version=${{ inputs.version }}
        annotations: |
          org.opencontainers.image.title=${{ inputs.imageTitle }}-migrations
          org.opencontainers.image.description=${{ inputs.imageDescription }}
          org.opencontainers.image.url=${{ inputs.repositoryUrl }}
          org.opencontainers.image.revision=${{ inputs.sha }}
          org.opencontainers.image.version=${{ inputs.version }}
        build-args: ${{ inputs.buildArgs }}
        secrets: ${{ inputs.secrets }}
        cache-from: type=gha, scope=${{ github.repository }}-migrations
        cache-to: type=gha, mode=max, scope=${{ github.repository }}-migrations
      
    - name: Verify image in registry
      id: verify-image
      shell: bash
      env:
        IMAGE: "${{ inputs.registry }}/${{ inputs.organizationName }}/${{ inputs.imageName }}"
        DIGEST: ${{ steps.publish.outputs.digest }}
      run: |
        set -euo pipefail

        if [ -z "$DIGEST" ]; then
          echo "::error::Docker push did not return a digest"
          exit 1
        fi

        echo "Verifying image exists: ${IMAGE}@${DIGEST}"
        if ! docker manifest inspect "${IMAGE}@${DIGEST}" > /dev/null 2>&1; then
          echo "::error::Image not found in registry after push"
          exit 1
        fi

        echo "::notice::Image verified in registry: ${IMAGE}@${DIGEST}"
        echo "verified_digest=${DIGEST}" >> "$GITHUB_OUTPUT"

    - name: sign container image
      run: |
        set -euo pipefail

        # Single source of truth: verified digest from previous step
        if [ -z "$VERIFIED_DIGEST" ]; then
          echo "::error::No verified digest available"
          exit 1
        fi

        echo "Signing image: ${IMAGE}@${VERIFIED_DIGEST}"
        cosign sign --key env://COSIGN_KEY "${IMAGE}@${VERIFIED_DIGEST}" --recursive=true --yes=true

        echo "Verifying signature..."
        cosign verify --key "${COSIGN_PUBLIC_KEY_URL}" "${IMAGE}@${VERIFIED_DIGEST}" || {
          echo "::error::Signature verification failed!"
          exit 1
        }
        echo "::notice::Image signed and verified successfully"
      shell: bash
      env:
        COSIGN_KEY: ${{ inputs.cosignKey }}
        COSIGN_PASSWORD: ${{ inputs.cosignPassword }}
        IMAGE: "${{ inputs.registry }}/${{ inputs.organizationName }}/${{ inputs.imageName }}"
        VERIFIED_DIGEST: ${{ steps.verify-image.outputs.verified_digest }}
        COSIGN_PUBLIC_KEY_URL: "https://raw.githubusercontent.com/innago-property-management/innago-cosign-public-key/refs/heads/main/cosign.pub"
      
    - name: sign migrations image
      if: ${{ inputs.migrationsDockerfilePath != '' }}
      run: |
        set -euo pipefail

        if [ -z "$DIGEST" ]; then
          echo "::error::Migrations image digest is not set"
          exit 1
        fi

        echo "Signing migrations image: ${IMAGE}@${DIGEST}"
        cosign sign --key env://COSIGN_KEY "${IMAGE}@${DIGEST}" --recursive=true --yes=true

        echo "Verifying migrations signature..."
        cosign verify --key "${COSIGN_PUBLIC_KEY_URL}" "${IMAGE}@${DIGEST}" || {
          echo "::error::Migrations signature verification failed!"
          exit 1
        }
        echo "::notice::Migrations image signed and verified successfully"
      shell: bash
      env:
        COSIGN_KEY: ${{ inputs.cosignKey }}
        COSIGN_PASSWORD: ${{ inputs.cosignPassword }}
        IMAGE: "${{ inputs.registry }}/${{ inputs.organizationName }}/${{ inputs.imageName }}-migrations"
        DIGEST: ${{ steps.publish-migrations.outputs.digest }}
        COSIGN_PUBLIC_KEY_URL: "https://raw.githubusercontent.com/innago-property-management/innago-cosign-public-key/refs/heads/main/cosign.pub"