name: "Build Python"
description: "Builds a Python app, installs dependencies, and runs tests"

inputs:
  version:
    required: true
    description: "Version"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip

    - name: Check for and install requirements.txt
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found. Skipping dependency installation."
        fi

    - name: Build distributable package
      shell: bash
      run: |
        python -m build
    
    # - name: Free disk space (after build & deps install)
    #   shell: bash
      # run: |
      #   sudo rm -rf /usr/local/lib/android \
      #     /opt/ghc \
      #     /usr/share/dotnet \
      #     /usr/local/share/boost

