name: "Push NuGet packages"
description: "Uploads NuGet packages to GitHub"
inputs:
  organization:
    description: 'GitHub organization for package registry'
    required: false
    default: 'innago-property-management'
  pushToken:
    required: true
    description: "GitHub token"
runs:
  using: "composite"
  steps:
    - name: Push Nuget packages
      shell: bash
      env: 
        PUSH_TOKEN: "${{ inputs.pushToken }}"
      run: |
        find . -path '**/bin/Release/*.nupkg' -print0 | while IFS= read -r -d $'\0' file; do 
          dotnet nuget push "$file" \
            --source "https://nuget.pkg.github.com/${{ inputs.organization }}/index.json" \
            --api-key "${PUSH_TOKEN}" \
            --skip-duplicate
        done