#!/usr/bin/env bash
# Deploy kaizen-sweep workflow to a target repository
#
# Usage:
#   ./scripts/deploy-kaizen-sweep.sh <repo-name> [--pr]
#
# Arguments:
#   repo-name   Name of repo in innago-property-management org (e.g., "cygnus")
#   --pr        Create a PR instead of direct push (for repos with branch protection)
#
# Examples:
#   ./scripts/deploy-kaizen-sweep.sh cygnus
#   ./scripts/deploy-kaizen-sweep.sh helm-charts --pr

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ORG="innago-property-management"
WORKFLOW_TEMPLATE="$REPO_ROOT/.github/workflows/kaizen-sweep-caller.yml"

usage() {
    echo "Usage: $0 <repo-name> [--pr]"
    echo ""
    echo "Deploy kaizen-sweep workflow to a target repository."
    echo ""
    echo "Arguments:"
    echo "  repo-name   Name of repo in $ORG org"
    echo "  --pr        Create a PR instead of direct push"
    exit 1
}

if [[ $# -lt 1 ]]; then
    usage
fi

REPO_NAME="$1"
CREATE_PR=false

if [[ "${2:-}" == "--pr" ]]; then
    CREATE_PR=true
fi

TARGET_REPO="$ORG/$REPO_NAME"

echo "=== Deploying kaizen-sweep to $TARGET_REPO ==="

# Step 1: Add kaizen-enabled topic
echo -n "Adding kaizen-enabled topic... "
if gh repo edit "$TARGET_REPO" --add-topic kaizen-enabled 2>/dev/null; then
    echo "done"
else
    echo "already present or failed"
fi

# Step 2: Get workflow content (base64 encoded)
WORKFLOW_CONTENT=$(base64 -i "$WORKFLOW_TEMPLATE")

# Step 3: Check if workflow already exists
EXISTING_SHA=$(gh api "repos/$TARGET_REPO/contents/.github/workflows/kaizen-sweep.yml" --jq '.sha' 2>/dev/null || echo "")

if $CREATE_PR; then
    echo "Creating PR for workflow..."

    # Clone, branch, commit, push, PR
    TEMP_DIR=$(mktemp -d)
    cd "$TEMP_DIR"

    git clone --depth 1 "git@github.com:$TARGET_REPO.git" repo
    cd repo
    git checkout -b add-kaizen-sweep-workflow

    mkdir -p .github/workflows
    cp "$WORKFLOW_TEMPLATE" .github/workflows/kaizen-sweep.yml

    git add .github/workflows/kaizen-sweep.yml
    git commit --no-gpg-sign -m "feat: add kaizen-sweep workflow for automated code improvements

Enables scheduled kaizen sweeps. The workflow calls the reusable
workflow from Oui-DELIVER for instant org-wide updates.

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>"

    git push -u origin add-kaizen-sweep-workflow

    PR_URL=$(gh pr create \
        --title "feat: add kaizen-sweep workflow" \
        --body "Enables automated kaizen sweeps for this repository.

## What this does
- Adds kaizen-sweep workflow that responds to dispatcher calls
- Uses @main ref for instant org-wide updates
- Requires: kaizen-enabled topic (already added)

---
Generated by deploy-kaizen-sweep.sh")

    echo "PR created: $PR_URL"

    # Cleanup
    cd /
    rm -rf "$TEMP_DIR"
else
    echo -n "Pushing workflow directly... "

    if [[ -n "$EXISTING_SHA" ]]; then
        # Update existing file
        gh api "repos/$TARGET_REPO/contents/.github/workflows/kaizen-sweep.yml" \
            -X PUT \
            -f message="fix: update kaizen-sweep workflow" \
            -f content="$WORKFLOW_CONTENT" \
            -f sha="$EXISTING_SHA" \
            --jq '.commit.sha' && echo " updated"
    else
        # Create new file
        gh api "repos/$TARGET_REPO/contents/.github/workflows/kaizen-sweep.yml" \
            -X PUT \
            -f message="feat: add kaizen-sweep workflow for automated code improvements" \
            -f content="$WORKFLOW_CONTENT" \
            --jq '.commit.sha' && echo " created"
    fi
fi

echo ""
echo "=== Deployment complete ==="
echo "Repo: $TARGET_REPO"
echo "Topic: kaizen-enabled"
echo "Workflow: .github/workflows/kaizen-sweep.yml"
