name: auto-pr
on:
  workflow_dispatch:
  
  push:
    branches-ignore:
      - main

permissions: 
  contents: read
  pull-requests: write
  
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # 5.0.1
      - name: Create GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 #v2.2.0
        with:
          app-id: ${{ vars.AUTO_PR_APP_ID }}
          private-key: ${{ secrets.AUTO_PR_APP_PRIVATE_KEY }}
      - name: pull-request
        uses: diillson/auto-pull-request@4cf50b3681cd76250f37841466e61e514a377064 #v1.0.1
        with:
          destination_branch: 'main'
          github_token: ${{ steps.app_token.outputs.token }}
