name: build-publish
on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true
        description: "github.actor"
      imageTitle:
        type: string
        required: true
        description: "github.event.repository.name"
      imageDescription:
        type: string
        required: true
        description: "github.event.repository.description"
      repositoryUrl:
        type: string
        required: true
        description: "github.event.repository.html_url"
      sha:
        type: string
        required: true
        description: "github.sha"
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: "Github token"
        required: true
      COSIGN_KEY:
        description: "Cosign key"
        required: true
      COSIGN_PASSWORD:
        description: "Cosign password"
        required: true
    inputs:
      username:
        type: string
        required: true
        description: "github.actor"
      imageTitle:
        type: string
        required: true
        description: "github.event.repository.name"
      imageDescription:
        type: string
        required: true
        description: "github.event.repository.description"
      repositoryUrl:
        type: string
        required: true
        description: "github.event.repository.html_url"
      sha:
        type: string
        required: true
        description: "github.sha"
jobs:
  version:
    uses: ./.github/workflows/semver.yml
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      pull-requests: write
    needs: version
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build
        uses: ./.github/actions/build-dotnet
        with:
          version: ${{ needs.version.outputs.version }}
          githubToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check licenses
        uses: ./.github/actions/check-licenses-action
      - name: Upload licenses
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          path: out
          overwrite: 'true'
      - name: Push Nuget package
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/push-nuget-packages
        with:
          githubToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate SBOM
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/generate-sbom-dotnet
      - name: Upload SBOMs
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          path: out
          overwrite: 'true'
      - name: Publish Container Image
        uses: ./.github/actions/build-publish-sign-docker
        with:
          registry: ghcr.io
          username: ${{ inputs.username }}
          password: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.version.outputs.version }}
          imageName: email-to-property-owner-id
          organizationName: innago-property-management
          imageTitle: ${{ inputs.imageTitle }}
          imageDescription: ${{ inputs.imageDescription }}
          repositoryUrl: ${{ inputs.repositoryUrl }}
          sha: ${{ inputs.sha }}
          cosignKey: ${{secrets.COSIGN_KEY}}
          cosignPassword: ${{secrets.COSIGN_PASSWORD}}