# .github/workflows/generate-provenance.yml

name: "Generate SLSA Provenance"

on:
  workflow_dispatch:
    inputs:
      artifact_path:
        required: false
        default: out
        description: "Path to build artifacts"
        type: string
  workflow_call:
    inputs:
      artifact_path:
        required: false
        default: out
        description: "Path to build artifacts"
        type: string

permissions:
  id-token: write
  contents: read
  actions: read
  attestations: write

jobs:
  generate-hashes:
    runs-on: ubuntu-latest
    outputs: 
      hashes: ${{ steps.hashes.outputs.hashes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Download a Build Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
        with: 
          path: ${{ inputs.artifact_path }}
          name: 'build-artifact'
      - name: Calculate Hashes
        id: hashes
        shell: bash
        env:
          artifact_path: ${{ inputs.artifact_path }}
        run: |
          shopt -s nullglob
          echo "hashes=$(sha256sum .github/*.y* .github/**/*.y* ${artifact_path}/**/* | base64 -w0)" >> "$GITHUB_OUTPUT"
  generate-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    needs: generate-hashes
    permissions: 
      attestations: write
      contents: read
      id-token: write
      actions: read
    with:
      base64-subjects: ${{ needs.generate-hashes.outputs.hashes }}
      private-repository: true