# .github/workflows/generate-provenance.yml

name: "Generate SLSA Provenance"

on:
  workflow_dispatch:
    inputs:
      artifact_path:
        required: true
        description: "Path to build artifacts"
        type: string

permissions:
  id-token: write # Required for signing the provenance.
  contents: read  # Required for checking out the repository.
  actions: read   # Required by the SLSA generator.

jobs:
  generate-provenance:
    runs-on: ubuntu-latest
    outputs: 
      slsa_artifact: ${{ steps.slsa.outputs.provenance-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate Hashes
        id: hashes
        shell: bash
        env:
          artifact_path: ${{ github.event.inputs.artifact_path }}
        run: |
          shopt -s nullglob
          # The input is accessed via the `github.event.inputs` context
          echo "HASHES=$(sha256sum .github/*.y* .github/**/*.y* ${artifact_path}/**/* | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Generate SLSA Provenance
        id: slsa
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
        with:
          base64-subjects: ${{ steps.hashes.outputs.HASHES }}
          private-repository: true