name: merge-checks

on:
  workflow_dispatch:
  workflow_call:
    inputs: 
      allowed_licenses_path:
        required: true
        description: "Path to the allowed licenses JSON file"
        type: string
      ignored_packages_path:
        required: true
        description: "Path to the ignored packages JSON file"
        type: string
    secrets: 
      githubToken:
        description: "Github token"
        required: true

permissions: 
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: semgrep-action
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d #v1
  secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    container:
      image: ghcr.io/gitleaks/gitleaks:latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: GitLeaks
        shell: bash
        env: 
          GITHUB_TOKEN: "${{ secrets.githubToken }}"
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          WORK_DIR="/__w/${{ github.repository_owner }}/${REPO_NAME}"
          CONTAINER_WORK_DIR="/__w/${REPO_NAME}/${REPO_NAME}"
          git config --global --add safe.directory "$WORK_DIR"
          git config --global --add safe.directory "$CONTAINER_WORK_DIR"
          gitleaks git --verbose --log-level trace  --log-opts="-n 10"
  vulnerabilities:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v4
        with:
          dotnet-version: |
            9.x
            10.x
      - name: Cache NuGet packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # 4.3.0
        with:
          path: ~/.nuget/packages        
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - shell: bash
        name: vulnerable
        env:
          GHCR_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.githubToken }}
          NuGetPackageSourceCredentials_github: "Username=${{ github.actor }};Password=${{ secrets.githubToken }}"
        run: |
          dotnet nuget add source \
            --name "github" \
            --username "$GHCR_USER" \
            --password "$GHCR_TOKEN" \
            --store-password-in-clear-text \
            "https://nuget.pkg.github.com/innago-property-management/index.json"
          
          dotnet restore
          
          dotnet list package --vulnerable --include-transitive 2>&1 | tee vuln.log
          cat vuln.log >> $GITHUB_STEP_SUMMARY
          
          if grep -iq -w -c "critical\|high\|moderate\|low" vuln.log; then
            COUNT=$(grep -ic -w "critical\|high\|moderate\|low" vuln.log)
            echo "Security: Vulnerabilities found on the log output: $COUNT"
            exit 1
          else
            echo "No vulnerabilities found"
            exit 0
          fi
  outdated:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v4
        with:
          dotnet-version: '9.x'
      - name: Cache NuGet packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # 4.3.0
        with:
          path: ~/.nuget/packages        
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install jq
        uses: dcarbone/install-jq-action@b7ef57d46ece78760b4019dbc4080a1ba2a40b45 #v3.2.0
      - name: Outdated Tool
        env:
          GHCR_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.githubToken }}
          NuGetPackageSourceCredentials_github: "Username=${{ github.actor }};Password=${{ secrets.githubToken }}"
        shell: bash
        run: |
          dotnet nuget add source \
            --name "github" \
            --username "$GHCR_USER" \
            --password "$GHCR_TOKEN" \
            --store-password-in-clear-text \
            "https://nuget.pkg.github.com/innago-property-management/index.json"
          
          PATH=/root/.dotnet/tools:$PATH
          dotnet tool install --global dotnet-outdated-tool
          
          dotnet restore
          
          solution=$(find . -type f -name '*.slnx')
        
          if [[ -z $solution ]]; then
            solution=$(find . -type f -name '*.sln')
          fi
          
          dotnet outdated "${solution}" \
            --output outdated.json \
            --fail-on-updates \
            --version-lock Major
      - shell: bash
        if: failure()
        name: Transform
        run: |
          cat outdated.json | jq '[.Projects[] | {"name": .Name, "package": (.TargetFrameworks[0].Dependencies[] | .Name ), "severity": (.TargetFrameworks[0].Dependencies[] | .UpgradeSeverity ), "latestVersion": (.TargetFrameworks[0].Dependencies[] | .LatestVersion  } ]' > outdatedProjects.json
      - uses: buildingcash/json-to-markdown-table-action@b442169239ef35f1dc4e5c8c3d47686c081a7e65 #v1.1.0
        if: failure()
        name: table
        id: table
        with:
          json_file_path: outdatedProjects.json
  licenses:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check licenses
        uses: innago-property-management/Oui-DELIVER/.github/actions/check-licenses-action@main
        with:
          allowed_licenses_path: "${{ inputs.allowed_licenses_path }}"
          ignored_packages_path: "${{ inputs.ignored_packages_path }}"
          githubToken: "${{ secrets.githubToken }}"
      - name: Upload licenses
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          path: out
          overwrite: 'true'
  enforceWarningsAsErrors:
    name: Check Warnings as Errors
    uses: innago-property-management/Oui-DELIVER/.github/workflows/enforce-treat-warnings-as-errors.yaml@main
        
